# FROM node:10
# Create image based on the official Node image from dockerhub
# FROM node:lts-buster-slim
FROM node:16.19
# FROM alpine:3.16

WORKDIR /usr/app/frontend
# WORKDIR  /usr/src/app

COPY package*.json ./

RUN npm install

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
# Get all the code needed to run the app
COPY . /usr/app/frontend

EXPOSE 3000

CMD ["npm", "start"]